### ISSUE TITLE
Map information

### ISSUE THREAD

**Issue by bbrito** [vita-epfl/trajnetplusplusdata#2]
Dear Trajnet team,

Is it already possible to get the map information or is it something that you are considering in a near future?

Best regards,
Bruno

**Comment by theDebugger811** [comment]
Hello,
    Currently, the TrajNet++ framework is focused on social interactions.  We might add the map information in the future.

Thanks
Parth

**Comment by bbrito** [comment]
Ok I understand. Thank you so much!
